In [1]:
import numpy as np
import pandas as pd 
import sympy as sy

In [5]:
#TRANSFORMANDO ARRAY EM 0 

v = [1,2,3,4]

vn = np.add(v, 5)

print(vn)

vn *= 0 

print(vn)

[6 7 8 9]
[0 0 0 0]


Exercício 1 - soma de matrizes


In [ ]:
mat_a = np.array([ [1,2,3], \
                  [4,5,6]])

mat_b = np.array([ [25, 67, 43],
                  [22, 13, 56]])

soma_mat = mat_a + mat_b

print(soma_mat)

[[26 69 46]
 [26 18 62]]


Exercício 2 - Multiplicação de Matrizes

Exercício 3 - Transposta de matriz

In [2]:
mat_a = np.array([ [1,2,3], [4,5,6], [10, 12, 13]])

transp_mat = np.transpose(mat_a)

print(transp_mat)

[[ 1  4 10]
 [ 2  5 12]
 [ 3  6 13]]


Exercício 4 - Traço de uma Matriz (diagonal)

In [30]:
mat_a = np.array([ [1,2,3], [4,5,6], [10, 12, 13]])

soma = 0

for i in range(len(mat_a)):
    soma += mat_a[i][i]
    
print(soma)

# ===================================================================
# Fazendo com np 

soma_2 = np.trace(mat_a)

print(f'Soma utilizando Np = {soma_2}')


19
Soma utilizando Np = 19


Exercício 5 - Determimante de uma matriz



In [ ]:
mat_a = np.array([ [1,2,3], [4,5,6], [7,8,9] ])

mat_new = []

"""
pra acessar os dois primeiros termos tenho que usar [i][:2]
AAAAAAAAAAAAAAAA NÃO AGUENTO MAIS 
"""
for i in range(len(mat_a)):
   linha = mat_a[i]
   nova_linha = linha[:2]
   mat_new.append(nova_linha)
    
mat_new = np.array(mat_new)

print(mat_new)

[[1 2]
 [4 5]
 [7 8]]


Calculando a determinante usando numoy & sympy

In [3]:
mat = np.array([ [1,2], [3,4] ])
det_1 = np.linalg.det(mat)
print(det_1)

matx = sy.Matrix([ [1,2], [3,4] ])
det_2 = matx.det()
print(det_2)


-2.0000000000000004
-2


Calculando a inversa
*Só é possível realizar o cálculo, caso a determinando seja diferente de 0

In [5]:
mat_inv = np.array([ [1,2], [3,4] ])
inv = np.linalg.inv(mat_inv)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Realizando operações com sistemas lineares


In [2]:
# Matriz de Coeficientes, representam os dados de entrada 
A = np.array([[2,3,2],
              [4,1,3],
              [1,2,5]])

In [8]:
# Matriz de termos constantes (representa os dados de saída)

B = np.array([1,3,9])


In [9]:
sis_linear = np.linalg.solve(A,B)

In [10]:
print(sis_linear)

[-0.74358974 -0.64102564  2.20512821]


In [ ]:
#Extraindo os valores do array pra cada variável
x_val, y_val, z_val = sis_linear

In [12]:
eq1 = np.isclose(2 * x_val + 3 * y_val + 2 * z_val, 1)
eq2 = np.isclose(4 * x_val + y_val + 3 * z_val, 3)
eq3 = np.isclose(x_val + 2 * y_val + 5 * z_val, 9)

In [13]:
eq1, eq2, eq3

(np.True_, np.True_, np.True_)

Exercício 1: Cálculo de Determinante

Calcule o determinante da matriz 3x3 abaixo. 

In [2]:
dsa_matriz_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

determinante = np.linalg.det(dsa_matriz_1)

print(f'A determinante da matriz é: {determinante}')

A determinante da matriz é: -9.51619735392994e-16


Exercício 2: Matriz Inversa de uma Matriz 2x2

Crie uma função em Python que receba uma matriz 2x2 e retorne sua inversa.

In [6]:
mat_2x2 = np.array([ [2,24], [45,67] ])

inversa = np.linalg.inv(mat_2x2)

print(f'A inversa dessa matriz é: {inversa}')


A inversa dessa matriz é: [[-0.07082452  0.02536998]
 [ 0.04756871 -0.00211416]]


 Exercício 3: Verificação de Determinante Zero

Verifique se o determinante da matriz 3x3 abaixo é zero e se a matriz tem inversa.

In [9]:
dsa_matriz_3 = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

determinante_0 = np.linalg.det(dsa_matriz_3)

if determinante_0 == 0:
    print('A matriz possui determinante = 0 ')
else:
    print(f'A determinante da matriz não é 0, e sim {determinante_0}')
    
# Não é possível calcular a inversa da matriz, pois sua determinante = 0 

A matriz possui determinante = 0 


EXERCÍCIO 4: Cálculo de Matriz Inversa com Numpy

Utilize a biblioteca Numpy para calcular a inversa de uma matriz 3x3. Considere esta matriz abaixo para o cálculo. Use try/except para tratar eventuais erros.

In [11]:
dsa_matriz_4 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

try:
    inversa_2 = np.linalg.inv(dsa_matriz_4)
    print('A inversa da matriz é:')
    print(f'{inversa_2}')
except:
    print('Não foi possível calcular a inversa da matriz, pois seu determinante não é diferente de 0 ')

A inversa da matriz é:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


Exercício 5: Determinante e Inversa de uma Matriz 4x4

Calcule o determinante e a inversa da matriz 4x4 abaixo, caso a inversa exista. 

In [12]:
dsa_matriz_5 = [[1, 0, 2, -1], [3, 0, 0, 5], [2, 1, 4, -3], [1, 0, 5, 0]]

determinante_5 = np.linalg.det(dsa_matriz_5)
print(f'A determinante da matriz é: {determinante_5}')

try:
    inversa_3 = np.linalg.inv(dsa_matriz_5)
    print('A inversa da matriz é:')
    print(f'{inversa_3}')
except:
    print('Não foi possível calcular a inversa da matriz, pois seu determinante não é diferente de 0 ')

A determinante da matriz é: 29.99999999999999
A inversa da matriz é:
[[ 0.83333333  0.16666667  0.         -0.33333333]
 [-2.5         0.1         1.          0.2       ]
 [-0.16666667 -0.03333333  0.          0.26666667]
 [-0.5         0.1        -0.          0.2       ]]
